### ISSUE TITLE
A slider for Fee

### ISSUE THREAD

**Issue by fajarvm** [nemfoundation/symbol-desktop-wallet#104]
It would have been a much better user experience to have a (scaled) slider for setting up the Fee instead of using the dropdown option.

**Comment by evias** [comment]
Our initial idea was to permit defining different _steps_ for fees payments. There is two variables here:

- when normal transaction, only **speed** will affect
- when aggregate transaction, the number of cosignatories needed will actually affect the fee needed, so that adds a dimension of **weight** that will affect the fee. Additionally "number of cosignatories" is not always trivial and REST guys are looking into providing better/different fees estimations.

Noting down the fact that a _slider_ may bring better usability versus our select dropdown _which does not let room for misuse/mismanagement on side of enduser_. We will assess whether a sliders is preferred with our UI team.

**Comment by decentraliser** [comment]
@fajarvm I don't agree that a scaled slider brings a much better UX

I think that a dropdown is the clearest input that we can have, while being much more simple to implement and maintain that a stepped slider (eg. adding/removing fee levels to a stepped slider might not be a trivial change). 

This is my own opinion, and this topic is open for internal discussions
