### ISSUE TITLE
Hardcoded config peers are not loaded/refreshed from rest endpoint

### ISSUE THREAD

**Issue by fboucquez** [nemfoundation/symbol-desktop-wallet#139]
At the moment, the list of peers is loaded from a [config file.](https://github.com/nemfoundation/symbol-desktop-wallet/blob/master/config/network.conf.json#L17)

This list is hard to maintain especially when supporting multiple network types when deploying the wallet in multiple environments (like private). 

![image](https://user-images.githubusercontent.com/5390558/77197594-3abfbd00-6ac4-11ea-87f3-ff7885bc8868.png)

Rest is now providing the list of known peers:

https://nemtech.github.io/symbol-openapi/#operation/getNodePeers
http://api-01.us-west-1.symboldev.network:3000/node/peers

The wallet could load the node peer list from the initial/default node and cache it in the database. If the default node is offline, the wallet could suggest another node from the stored list. 
I would remove the static list from the config file and let the bootstrap step to load from rest or database when offline.

The only problem I found in the rest endpoint is the missing rest URLs for the peer. We can assume  `HTTP://` + `host` + `:3000` for now but this would probably change per node. I guess we would like to use standard 80 or 443 in the future. @dgarcia360

If the node peers list is automatically loaded and updated from rest, the user need for adding custom node peer URLs in the popup is reduced.  The list would be kept up to date. I would validate the nodes by checking if they are online, same generation hash and network type.

I think the final end goal is to reduce the network.conf.json to just a default rest endpoint URL. The wallet can load everything else from rest and use the database for offline resilience. Then if you want to deploy the wallet on top of a private network, just set the default URL in the config file and everything should work.

**Comment by evias** [comment]
I dont think port 80 or 443 are likely to be used for the REST API.

3000 is fine as a default but users that are using different ports should be able to explicitely specify the port number.

Point about network.conf.json is correct. This file should at most contain a list of **whitelisted** default nodes + generation hash. These whitelisted nodes are mostly _owned_ by the wallet publisher and permit to improve availability. Additionally, online builds are configured with this file so that if we want to publish a online build of the wallet _with different network config_, this is how we will do it.

All network properties should probably be removed from the network.conf.json.

**Comment by evias** [comment]
fixed with merge of #177
