### ISSUE TITLE
Prettier set-up

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/symbol-desktop-wallet#243]
Set-up prettier for the repo linting to be cross-editor friendly

**Comment by fboucquez** [comment]
These are the consideration we had in the TS SDK:

https://github.com/nemtech/symbol-sdk-typescript-javascript/pull/531

We can use the ts PR for the initial setup too. Wallet will be a little bit harder due to Vue, Vue seems supported by prettier. We should remove the tslint dev dependency, we are using estlint with ts plugin
