### ISSUE TITLE
Mosaic namespace resolution when mosaic is received as alias

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/symbol-desktop-wallet#275]
This transfer has sent  @symbol.xym::6 from the CLI, symbol.xym should show instead of a mosaicId

![image](https://user-images.githubusercontent.com/36499647/79973048-738af180-84c9-11ea-88d8-1770f58103ed.png)

**Comment by fboucquez** [comment]
is this happening after 177 pr merge?

**Comment by fboucquez** [comment]
One issue we need to consider is that when showing old transactions, the aliases could have been expired. The transaction details may need to dig into the block's recipients in order to know the right divisibility and alias names (unsure if this is possible though, maybe the namespace info is really gone?)

**Comment by decentraliser** [comment]
no!

I let you open another issue for expired namespaces if you think it needs a fix @fboucquez
