### ISSUE TITLE
Mnemonic Import copy/paste bug

### ISSUE THREAD

**Issue by evias** [nemfoundation/symbol-desktop-wallet#321]
When pasting a 24-words mnemonic into the account import page i get the following bug as shown in screenshot ..

<img width="1078" alt="Screenshot 2020-05-02 at 10 28 30 PM" src="https://user-images.githubusercontent.com/141805/80891452-5bcf1c80-8cc4-11ea-8f4e-8f81ff93a942.png">

**Comment by vincent-lee90** [comment]
This problem is caused by CSS global pollution. 
Reproduce:
1.visit http://localhost:8080/#/profiles/create/showMnemonic
2.visit http://localhost:8080/#/profiles/import/importMnemonic
as we see, the different routes have different components, but the css  class name may be the same when our project is big enough , at this time, the css pattern will be polluted.

the [css](https://github.com/nemfoundation/symbol-desktop-wallet/blob/6330baa8c54fb44c9d6ec860c7ea639cfe9a9a11/src/views/pages/profiles/create-profile/show-mnemonic/ShowMnemonic.less#L31) in step 1  influenced the step2 , they should be two separate components .
So we need to add components scoped. 
The [pr#320](https://github.com/nemfoundation/symbol-desktop-wallet/pull/320) has solved it .
