### ISSUE TITLE
Addresses pretty format not accepted in recipient field

### ISSUE THREAD

**Issue by DrCryptos** [nemfoundation/symbol-desktop-wallet#449]
When creating a transaction for sending tokens, if you enter the wallet address with "-", an error is generated about the wrong address format. If you remove "-" from the address, then there are no problems

Address: TC7RGI-4ERQ4M-SG5UYA-AS5CC2–32JR3W-FORVOT-2KVD
Result:
![image](https://user-images.githubusercontent.com/67805522/86532987-9dec2880-bed6-11ea-96e1-e8fc6ddb8e57.png)

**Comment by DrCryptos** [comment]
Mistakenly closed

**Comment by bassemmagdy** [comment]
non-reproducible

**Comment by evias** [comment]
Hello @DrCryptos,

Thank you for your report!! 

With our latest [release v0.12](https://github.com/nemfoundation/symbol-desktop-wallet/releases/tag/v0.12.0), this bug is not reproducible anymore. Also, mind that _addresses format_ changed from 40 characters to 39 characters with latest server changes, which mean that for trying to reproduce this you will also need to generate the new account.

Please, feel free to re-open the issue if you find yourself encountering the same validation error again :+1: 

And thank you for participating!
