### ISSUE TITLE
ModalHarvestingSetupWizard implementation [design pending]

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/symbol-desktop-wallet#75]
Components:

src/views/modals/ModalHarvestingSetupWizard
Task description:
The harvesting setup wizard should be composed of multiple forms such that following actionable items are executed:

Actionable Items:
- [x]  FormAccountLinkTransaction (@decentraliser)
- [x]  FormPersistentDelegationRequestTransaction (@decentraliser)

Related requests from other issues:
- [x] Should include a way to know the delegated private key
- [ ] The vested balance should be displayed

**Comment by NemTechCN** [comment]
Delegated harvesting operation requires the client three accounts:

- Main account:  delegates importance sore to obtain real revenue
- Announcer account: helps the main account to make a request so that the main account can be hidden
- Remote account: a proxy private key that delegates to the node configuration

In this program model, the main account is the current account.There are two options for an Announcer account: One is to default to the current account. The other requires you to declare a private key temporary import to Announce tx .

**The model design is as follows：**
1.Through harvesting dashboard, check the configuration status.  By switching the list, you can see the latest revenue list, the list of remote account operation transactions, and the list of remote request transactions.
![1](https://user-images.githubusercontent.com/45383558/79725882-7a283600-831c-11ea-9cfd-50e25f4f06ce.png)

2.Link and unlink configuration for remote account
![2](https://user-images.githubusercontent.com/45383558/79726160-f0c53380-831c-11ea-8235-85e4a3a1677a.png)

3.Initiate a delegate request to the configuration node
![3](https://user-images.githubusercontent.com/45383558/79726284-210cd200-831d-11ea-9bda-2058f70d864a.png)

Expect more advices.
Thank you
